import { DecisionTreeData } from "../models/types";

export function oilDrillingExample(): DecisionTreeData {
  return {
    rootId: "root",
    metadata: {
      name: "Perforación de pozo",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      mode: "maximize",
    },
    nodes: {
      root: {
        id: "root",
        type: "decision",
        label: "Perforar pozo",
        payoff: null,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: null,
        childIds: ["drill", "no_drill"],
        probability: null,
        collapsed: false,
        customFields: {},
      },
      drill: {
        id: "drill",
        type: "chance",
        label: "Perforar",
        payoff: null,
        cost: 200000,
        time: "6 meses",
        expectedValue: null,
        isOptimal: false,
        parentId: "root",
        childIds: ["oil", "dry"],
        probability: null,
        collapsed: false,
        customFields: {},
      },
      oil: {
        id: "oil",
        type: "end",
        label: "Hay petroleo",
        payoff: 1000000,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: "drill",
        childIds: [],
        probability: 0.6,
        collapsed: false,
        customFields: {},
      },
      dry: {
        id: "dry",
        type: "end",
        label: "Pozo seco",
        payoff: -500000,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: "drill",
        childIds: [],
        probability: 0.4,
        collapsed: false,
        customFields: {},
      },
      no_drill: {
        id: "no_drill",
        type: "end",
        label: "No perforar",
        payoff: 0,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: "root",
        childIds: [],
        probability: null,
        collapsed: false,
        customFields: {},
      },
    },
  };
}

export function productLaunchExample(): DecisionTreeData {
  return {
    rootId: "root",
    metadata: {
      name: "Lanzamiento de producto",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      mode: "maximize",
    },
    nodes: {
      root: {
        id: "root",
        type: "decision",
        label: "Lanzar producto",
        payoff: null,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: null,
        childIds: ["launch", "no_launch"],
        probability: null,
        collapsed: false,
        customFields: {},
      },
      launch: {
        id: "launch",
        type: "chance",
        label: "Lanzar",
        payoff: null,
        cost: 150000,
        time: "3 meses",
        expectedValue: null,
        isOptimal: false,
        parentId: "root",
        childIds: ["high_demand", "med_demand", "low_demand"],
        probability: null,
        collapsed: false,
        customFields: {},
      },
      high_demand: {
        id: "high_demand",
        type: "end",
        label: "Demanda alta",
        payoff: 500000,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: "launch",
        childIds: [],
        probability: 0.3,
        collapsed: false,
        customFields: {},
      },
      med_demand: {
        id: "med_demand",
        type: "end",
        label: "Demanda media",
        payoff: 100000,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: "launch",
        childIds: [],
        probability: 0.5,
        collapsed: false,
        customFields: {},
      },
      low_demand: {
        id: "low_demand",
        type: "end",
        label: "Demanda baja",
        payoff: -200000,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: "launch",
        childIds: [],
        probability: 0.2,
        collapsed: false,
        customFields: {},
      },
      no_launch: {
        id: "no_launch",
        type: "end",
        label: "No lanzar",
        payoff: 0,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: "root",
        childIds: [],
        probability: null,
        collapsed: false,
        customFields: {},
      },
    },
  };
}

export function vacaMuertaDevelopmentExample(): DecisionTreeData {
  const now = new Date().toISOString();
  const base = {
    payoff: null,
    cost: null,
    time: null,
    expectedValue: null,
    isOptimal: false,
    collapsed: false,
    customFields: {},
  };

  const chance = (
    id: string,
    label: string,
    parentId: string | null,
    childIds: string[],
    probability: number | null,
    cost: number | null = 40,
    customFields: Record<string, string | number | null> = {}
  ): DecisionTreeData["nodes"][string] => ({
    ...base,
    id,
    type: "chance",
    label,
    cost,
    time: cost ? "MM$" : null,
    parentId,
    childIds,
    probability,
    customFields,
  });

  const terminal = (
    id: string,
    label: string,
    parentId: string,
    probability: number,
    outcome: number,
    investment = 160
  ): DecisionTreeData["nodes"][string] => ({
    ...base,
    id,
    type: "end",
    label,
    // El Excel profesional calcula el EMV con el outcome bruto de desarrollo;
    // la inversión terminal se muestra como dato auditivo/neto, no se resta en
    // el rollback principal. Las inversiones de piloto sí entran como cost=40.
    payoff: outcome,
    cost: null,
    time: "MM$",
    parentId,
    childIds: [],
    probability,
    customFields: {
      Outcome: `${outcome} MM$`,
      Inversión: `${investment} MM$`,
      Neto: `${outcome - investment} MM$`,
    },
  });

  const noDevelop = (id: string, parentId: string, probability: number): DecisionTreeData["nodes"][string] => ({
    ...base,
    id,
    type: "end",
    label: "No desarrollar",
    payoff: 0,
    cost: null,
    time: "MM$",
    parentId,
    childIds: [],
    probability,
    customFields: { Outcome: "0 MM$", Inversión: "0 MM$", Neto: "0 MM$" },
  });

  return {
    rootId: "vm_root",
    metadata: {
      name: "Desarrollo Vaca Muerta",
      createdAt: now,
      updatedAt: now,
      mode: "maximize",
    },
    nodes: {
      vm_root: {
        ...base,
        id: "vm_root",
        type: "decision",
        label: "Plan piloto VM",
        parentId: null,
        childIds: ["vm_pilot", "vm_withdraw"],
        probability: null,
      },
      vm_pilot: chance("vm_pilot", "Pilot 1", "vm_root", ["vm_p1_success", "vm_p1_fail"], null, 40, {
        "COS Pilot 1": "30%",
        "Costo piloto": "40 MM$",
        "NPV por área": "530 MM$",
      }),
      vm_withdraw: {
        ...base,
        id: "vm_withdraw",
        type: "end",
        label: "Retirarse",
        payoff: 0,
        cost: null,
        time: "MM$",
        parentId: "vm_root",
        childIds: [],
        probability: null,
        customFields: {},
      },

      vm_p1_success: chance("vm_p1_success", "P1 Success + P2", "vm_pilot", ["vm_p2_success_a", "vm_p2_fail_a"], 0.30),
      vm_p1_fail: chance("vm_p1_fail", "P1 Fail + P2", "vm_pilot", ["vm_p2_success_b", "vm_p2_fail_b"], 0.70),

      vm_p2_success_a: chance("vm_p2_success_a", "P2 Success + P3", "vm_p1_success", ["vm_p3_success_a", "vm_p3_fail_a"], 0.25),
      vm_p2_fail_a: chance("vm_p2_fail_a", "P2 Fail + P3", "vm_p1_success", ["vm_p3_success_b", "vm_p3_fail_b"], 0.75),
      vm_p2_success_b: chance("vm_p2_success_b", "P2 Success + P3", "vm_p1_fail", ["vm_p3_success_c", "vm_p3_fail_c"], 0.25),
      vm_p2_fail_b: chance("vm_p2_fail_b", "P2 Fail + P3", "vm_p1_fail", ["vm_p3_success_d", "vm_no_develop"], 0.75),

      vm_p3_success_a: chance("vm_p3_success_a", "P3 Success + P4", "vm_p2_success_a", ["vm_dev4_a", "vm_dev3_a"], 0.22),
      vm_p3_fail_a: chance("vm_p3_fail_a", "P3 Fail + P4", "vm_p2_success_a", ["vm_dev3_b", "vm_dev2_a"], 0.78),
      vm_p3_success_b: chance("vm_p3_success_b", "P3 Success + P4", "vm_p2_fail_a", ["vm_dev3_c", "vm_dev2_b"], 0.19),
      vm_p3_fail_b: chance("vm_p3_fail_b", "P3 Fail + P4", "vm_p2_fail_a", ["vm_dev2_c", "vm_dev1_a"], 0.81),
      vm_p3_success_c: chance("vm_p3_success_c", "P3 Success + P4", "vm_p2_success_b", ["vm_dev3_d", "vm_dev2_d"], 0.22),
      vm_p3_fail_c: chance("vm_p3_fail_c", "P3 Fail + P4", "vm_p2_success_b", ["vm_dev2_e", "vm_dev1_b"], 0.78),
      vm_p3_success_d: chance("vm_p3_success_d", "P3 Success + P4", "vm_p2_fail_b", ["vm_dev2_f", "vm_dev1_c"], 0.16),

      vm_dev4_a: terminal("vm_dev4_a", "Dev 4 áreas", "vm_p3_success_a", 0.19, 2120),
      vm_dev3_a: terminal("vm_dev3_a", "Dev 3 áreas", "vm_p3_success_a", 0.81, 1590),
      vm_dev3_b: terminal("vm_dev3_b", "Dev 3 áreas", "vm_p3_fail_a", 0.16, 1590),
      vm_dev2_a: terminal("vm_dev2_a", "Dev 2 áreas", "vm_p3_fail_a", 0.84, 1060),
      vm_dev3_c: terminal("vm_dev3_c", "Dev 3 áreas", "vm_p3_success_b", 0.16, 1590),
      vm_dev2_b: terminal("vm_dev2_b", "Dev 2 áreas", "vm_p3_success_b", 0.84, 1060),
      vm_dev2_c: terminal("vm_dev2_c", "Dev 2 áreas", "vm_p3_fail_b", 0.13, 1060),
      vm_dev1_a: terminal("vm_dev1_a", "Dev 1 área", "vm_p3_fail_b", 0.87, 530),
      vm_dev3_d: terminal("vm_dev3_d", "Dev 3 áreas", "vm_p3_success_c", 0.19, 1590),
      vm_dev2_d: terminal("vm_dev2_d", "Dev 2 áreas", "vm_p3_success_c", 0.81, 1060),
      vm_dev2_e: terminal("vm_dev2_e", "Dev 2 áreas", "vm_p3_fail_c", 0.16, 1060),
      vm_dev1_b: terminal("vm_dev1_b", "Dev 1 área", "vm_p3_fail_c", 0.84, 530),
      vm_dev2_f: terminal("vm_dev2_f", "Dev 2 áreas", "vm_p3_success_d", 0.13, 1060),
      vm_dev1_c: terminal("vm_dev1_c", "Dev 1 área", "vm_p3_success_d", 0.87, 530),
      vm_no_develop: noDevelop("vm_no_develop", "vm_p2_fail_b", 0.84),
    },
  };
}

export function workoverExample(): DecisionTreeData {
  return {
    rootId: "wo_root",
    metadata: {
      name: "Workover de pozo",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      mode: "minimize",
    },
    nodes: {
      wo_root: {
        id: "wo_root",
        type: "decision",
        label: "Intervenir pozo?",
        payoff: null,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: null,
        childIds: ["wo_do", "wo_no"],
        probability: null,
        collapsed: false,
        customFields: {},
      },
      wo_do: {
        id: "wo_do",
        type: "chance",
        label: "Hacer workover",
        payoff: null,
        cost: 150000,
        time: "45 dias",
        expectedValue: null,
        isOptimal: false,
        parentId: "wo_root",
        childIds: ["wo_ok", "wo_fail"],
        probability: null,
        collapsed: false,
        customFields: { "Inversion inicial": 150000 },
      },
      wo_ok: {
        id: "wo_ok",
        type: "chance",
        label: "Resultado operativo",
        payoff: null,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: "wo_do",
        childIds: ["wo_high", "wo_med"],
        probability: 0.65,
        collapsed: false,
        customFields: {},
      },
      wo_high: {
        id: "wo_high",
        type: "end",
        label: "Alta produccion",
        payoff: 80000,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: "wo_ok",
        childIds: [],
        probability: 0.6,
        collapsed: false,
        customFields: { "Precio petroleo": "USD 65/bbl" },
      },
      wo_med: {
        id: "wo_med",
        type: "end",
        label: "Produccion media",
        payoff: 180000,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: "wo_ok",
        childIds: [],
        probability: 0.4,
        collapsed: false,
        customFields: { "Precio petroleo": "USD 55/bbl" },
      },
      wo_fail: {
        id: "wo_fail",
        type: "decision",
        label: "Ante falla operativa",
        payoff: null,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: "wo_do",
        childIds: ["wo_retry", "wo_abandon"],
        probability: 0.35,
        collapsed: false,
        customFields: {},
      },
      wo_retry: {
        id: "wo_retry",
        type: "end",
        label: "Reintervenir",
        payoff: 450000,
        cost: 120000,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: "wo_fail",
        childIds: [],
        probability: null,
        collapsed: false,
        customFields: { OPEX: 120000 },
      },
      wo_abandon: {
        id: "wo_abandon",
        type: "end",
        label: "Abandonar pozo",
        payoff: 250000,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: "wo_fail",
        childIds: [],
        probability: null,
        collapsed: false,
        customFields: {},
      },
      wo_no: {
        id: "wo_no",
        type: "end",
        label: "No intervenir",
        payoff: 320000,
        cost: null,
        time: null,
        expectedValue: null,
        isOptimal: false,
        parentId: "wo_root",
        childIds: [],
        probability: null,
        collapsed: false,
        customFields: { "OPEX anual": 220000 },
      },
    },
  };
}
